# -*- coding: utf-8 -*-
"""Conteudo: Dicionarios em Python."""

from ..tema import TEMA_PYTHON

SPEC = {
    "tema": TEMA_PYTHON,
    "topico": "DICIONARIOS",
    "destaque": "EM PYTHON",
    "subtitulo": "Guia completo com exemplos, resultados e explicacoes",
    "simbolo": "{ }",
    "blocos": [
        {"tipo": "secao", "titulo": "O que e um dicionario?"},
        {"tipo": "checks", "itens": [
            "Dicionarios armazenam dados em pares <b>chave: valor</b>.",
            "Cada chave deve ser unica (e imutavel).",
            "Os valores podem ser de qualquer tipo.",
            "Sao mutaveis: podemos adicionar, alterar e remover itens.",
            "Muito usados para representar dados reais do mundo.",
        ]},

        {"tipo": "secao", "titulo": "Criando dicionarios"},
        {"tipo": "codigo", "titulo": "Formas de criar um dicionario", "linhas": [
            ("aluno = {'nome': 'Ana', 'idade': 20, 'curso': 'Python'}", "# dados do aluno"),
            ("vazio = {}", "# dicionario vazio"),
            ("pessoa = dict(nome='Joao', idade=28, cidade='SP')", "# usando dict()"),
            ("copia = aluno.copy()", "# copia rasa do dicionario"),
        ]},

        {"tipo": "secao", "titulo": "Operacoes e analise de dicionarios"},
        {"tipo": "paragrafo",
         "texto": "Exemplos considerando <b>dados = {'nome': 'Ana', 'idade': 20, "
                  "'curso': 'Python'}</b>."},
        {"tipo": "tabela",
         "cabecalho": ["Comando", "Resultado", "Explicacao"],
         "larguras": [0.30, 0.26, 0.44],
         "mono": [0], "resultado": 1,
         "linhas": [
            ["dados['nome']", "'Ana'", "Acessa o valor da chave 'nome'."],
            ["dados['idade']", "20", "Acessa o valor da chave 'idade'."],
            ["dados.get('curso')", "'Python'", "Retorna o valor da chave. Evita erro se ela nao existir."],
            ["dados.get('telefone')", "None", "Como 'telefone' nao existe, retorna None."],
            ["dados.get('tel', 'N/I')", "'N/I'", "Retorna o valor padrao quando a chave nao existe."],
            ["dados['idade'] = 21", "(altera)", "Altera o valor de uma chave existente."],
            ["dados['email'] = 'a@x.com'", "(adiciona)", "Adiciona um novo par chave:valor."],
            ["del dados['curso']", "(remove)", "Remove o par da chave informada."],
            ["dados.pop('idade')", "20", "Remove o par e retorna o valor removido."],
            ["dados.pop('tel', None)", "None", "Remove a chave se existir; senao retorna o padrao."],
            ["'nome' in dados", "True", "Verifica se a chave existe no dicionario."],
            ["'tel' in dados", "False", "A chave 'tel' nao existe no dicionario."],
            ["dados.keys()", "dict_keys([...])", "Retorna todas as chaves do dicionario."],
            ["dados.values()", "dict_values([...])", "Retorna todos os valores do dicionario."],
            ["dados.items()", "dict_items([...])", "Retorna pares (chave, valor) como tuplas."],
            ["len(dados)", "3", "Retorna a quantidade de pares chave:valor."],
            ["dados.clear()", "{}", "Remove todos os itens do dicionario."],
            ["dados.copy()", "{...}", "Cria uma copia rasa do dicionario."],
            ["dados.update({'uf': 'RJ'})", "{...}", "Atualiza ou adiciona pares de outro dicionario."],
            ["dados.setdefault('pais', 'BR')", "'BR'", "Adiciona a chave com padrao se nao existir."],
         ]},

        {"tipo": "secao", "titulo": "Percorrendo dicionarios"},
        {"tipo": "codigo", "titulo": "Tres formas de iterar", "linhas": [
            ("# apenas as chaves", None),
            ("for chave in dados:", None),
            ("    print(chave)", None),
            ("", None),
            ("# apenas os valores", None),
            ("for valor in dados.values():", None),
            ("    print(valor)", None),
            ("", None),
            ("# chaves e valores ao mesmo tempo", None),
            ("for chave, valor in dados.items():", None),
            ("    print(chave, '->', valor)", None),
        ]},

        {"tipo": "secao", "titulo": "Dicionarios aninhados"},
        {"tipo": "codigo", "titulo": "Dicionario dentro de dicionario", "linhas": [
            ("aluno = {", None),
            ("    'nome': 'Ana',", None),
            ("    'contato': {", None),
            ("        'email': 'ana@email.com',", None),
            ("        'telefone': '11 99999-9999'", None),
            ("    },", None),
            ("    'notas': [8.5, 9.0, 7.0]", None),
            ("}", None),
            ("print(aluno['contato']['email'])", "# ana@email.com"),
            ("print(aluno['notas'][0])", "# 8.5"),
        ]},

        {"tipo": "secao", "titulo": "Metodos uteis (resumo)"},
        {"tipo": "tabela",
         "cabecalho": ["Metodo", "O que faz"],
         "larguras": [0.28, 0.72], "mono": [0],
         "linhas": [
            ["keys()", "Retorna todas as chaves."],
            ["values()", "Retorna todos os valores."],
            ["items()", "Retorna pares (chave, valor)."],
            ["get()", "Acessa um valor com seguranca."],
            ["update()", "Atualiza ou adiciona pares."],
            ["pop()", "Remove e retorna o valor."],
            ["popitem()", "Remove o ultimo par inserido."],
            ["clear()", "Remove todos os itens."],
            ["copy()", "Cria uma copia rasa."],
         ]},

        {"tipo": "secao", "titulo": "Exercicio: sistema de biblioteca"},
        {"tipo": "paragrafo",
         "texto": "Um sistema que gerencia livros, onde <b>cada livro e um "
                  "dicionario</b>. Permite cadastrar, listar, buscar, emprestar, "
                  "devolver e remover. Cada livro guarda: titulo, autor, ano, "
                  "genero e disponivel (True/False)."},
        {"tipo": "codigo", "titulo": "biblioteca.py", "linhas": [
            ("biblioteca = []  # cada livro e um dicionario", None),
            ("", None),
            ("def cadastrar():", None),
            ("    livro = {", None),
            ("        'titulo': input('Titulo: '),", None),
            ("        'autor': input('Autor: '),", None),
            ("        'ano': input('Ano: '),", None),
            ("        'genero': input('Genero: '),", None),
            ("        'disponivel': True,", None),
            ("    }", None),
            ("    biblioteca.append(livro)", None),
            ("    print('Livro cadastrado!')", None),
            ("", None),
            ("def listar():", None),
            ("    if not biblioteca:", None),
            ("        print('Nenhum livro cadastrado.')", None),
            ("        return", None),
            ("    for livro in biblioteca:", None),
            ("        estado = 'Disponivel' if livro['disponivel'] else 'Emprestado'", None),
            ("        print(livro['titulo'], '-', livro['autor'], '(', estado, ')')", None),
            ("", None),
            ("def buscar():", None),
            ("    termo = input('Titulo buscado: ').lower()", None),
            ("    for livro in biblioteca:", None),
            ("        if termo in livro['titulo'].lower():", None),
            ("            print(livro)", None),
            ("", None),
            ("def emprestar():", None),
            ("    termo = input('Titulo: ').lower()", None),
            ("    for livro in biblioteca:", None),
            ("        if livro['titulo'].lower() == termo and livro['disponivel']:", None),
            ("            livro['disponivel'] = False", None),
            ("            print('Emprestimo realizado!')", None),
            ("            return", None),
            ("    print('Livro indisponivel.')", None),
            ("", None),
            ("# (devolver e remover seguem a mesma logica, mudando o estado/lista)", None),
            ("", None),
            ("while True:", None),
            ("    print('1-Cadastrar 2-Listar 3-Buscar 4-Emprestar 7-Sair')", None),
            ("    opcao = input('Escolha: ')", None),
            ("    if opcao == '1': cadastrar()", None),
            ("    elif opcao == '2': listar()", None),
            ("    elif opcao == '3': buscar()", None),
            ("    elif opcao == '4': emprestar()", None),
            ("    elif opcao == '7': break", None),
        ]},

        {"tipo": "callout", "titulo": "O que praticamos aqui",
         "texto": [
            "Usamos dicionarios para representar dados de forma estruturada.",
            "Cada livro e identificado por suas chaves (titulo, autor, ano...).",
            "Exploramos inclusao, busca, atualizacao e remocao de itens.",
            "Combinamos dicionarios com listas, booleanos e funcoes.",
         ]},

        {"tipo": "callout", "titulo": "Dica final + boas praticas",
         "cor": "#FFD43B",
         "texto": [
            "Dicionarios modelam dados do mundo real com clareza.",
            "Use chaves significativas e consistentes; evite duplicadas.",
            "Prefira .get() para acessos seguros (sem erro).",
            "Mantenha o codigo organizado em funcoes pequenas.",
         ]},
    ],
}
