# -*- coding: utf-8 -*-
"""Conteúdo: Dicionários em Python."""

from ..tema import TEMA_PYTHON

SPEC = {
    "tema": TEMA_PYTHON,
    "topico": "DICIONARIOS",
    "destaque": "EM PYTHON",
    "subtitulo": "Guia completo com exemplos, resultados e explicações",
    "simbolo": "{ }",
    "blocos": [
        {"tipo": "secao", "titulo": "O que é um dicionário?"},
        {"tipo": "checks", "itens": [
            "Dicionários armazenam dados em pares <b>chave: valor</b>.",
            "Cada chave deve ser única (e imutável).",
            "Os valores podem ser de qualquer tipo.",
            "São mutáveis: podemos adicionar, alterar e remover itens.",
            "Muito usados para representar dados reais do mundo.",
        ]},

        {"tipo": "secao", "titulo": "Criando dicionários"},
        {"tipo": "codigo", "titulo": "Formas de criar um dicionário", "linhas": [
            ("aluno = {'nome': 'Ana', 'idade': 20, 'curso': 'Python'}", "# dados do aluno"),
            ("vazio = {}", "# dicionário vazio"),
            ("pessoa = dict(nome='Joao', idade=28, cidade='SP')", "# usando dict()"),
            ("copia = aluno.copy()", "# cópia rasa do dicionário"),
        ]},

        {"tipo": "secao", "titulo": "Operações e análise de dicionários"},
        {"tipo": "paragrafo",
         "texto": "Exemplos considerando <b>dados = {'nome': 'Ana', 'idade': 20, "
                  "'curso': 'Python'}</b>."},
        {"tipo": "tabela",
         "cabecalho": ["Comando", "Resultado", "Explicação"],
         "larguras": [0.30, 0.26, 0.44],
         "mono": [0], "resultado": 1,
         "linhas": [
            ["dados['nome']", "'Ana'", "Acessa o valor da chave 'nome'."],
            ["dados['idade']", "20", "Acessa o valor da chave 'idade'."],
            ["dados.get('curso')", "'Python'", "Retorna o valor da chave. Evita erro se ela não existir."],
            ["dados.get('telefone')", "None", "Como 'telefone' não existe, retorna None."],
            ["dados.get('tel', 'N/I')", "'N/I'", "Retorna o valor padrão quando a chave não existe."],
            ["dados['idade'] = 21", "(altera)", "Altera o valor de uma chave existente."],
            ["dados['email'] = 'a@x.com'", "(adiciona)", "Adiciona um novo par chave:valor."],
            ["del dados['curso']", "(remove)", "Remove o par da chave informada."],
            ["dados.pop('idade')", "20", "Remove o par e retorna o valor removido."],
            ["dados.pop('tel', None)", "None", "Remove a chave se existir; senão retorna o padrão."],
            ["'nome' in dados", "True", "Verifica se a chave existe no dicionário."],
            ["'tel' in dados", "False", "A chave 'tel' não existe no dicionário."],
            ["dados.keys()", "dict_keys([...])", "Retorna todas as chaves do dicionário."],
            ["dados.values()", "dict_values([...])", "Retorna todos os valores do dicionário."],
            ["dados.items()", "dict_items([...])", "Retorna pares (chave, valor) como tuplas."],
            ["len(dados)", "3", "Retorna a quantidade de pares chave:valor."],
            ["dados.clear()", "{}", "Remove todos os itens do dicionário."],
            ["dados.copy()", "{...}", "Cria uma cópia rasa do dicionário."],
            ["dados.update({'uf': 'RJ'})", "{...}", "Atualiza ou adiciona pares de outro dicionário."],
            ["dados.setdefault('pais', 'BR')", "'BR'", "Adiciona a chave com padrão se não existir."],
         ]},

        {"tipo": "secao", "titulo": "Percorrendo dicionários"},
        {"tipo": "codigo", "titulo": "Três formas de iterar", "linhas": [
            ("# apenas as chaves", None),
            ("for chave in dados:", None),
            ("    print(chave)", None),
            ("", None),
            ("# apenas os valores", None),
            ("for valor in dados.values():", None),
            ("    print(valor)", None),
            ("", None),
            ("# chaves e valores ao mesmo tempo", None),
            ("for chave, valor in dados.items():", None),
            ("    print(chave, '->', valor)", None),
        ]},

        {"tipo": "secao", "titulo": "Dicionários aninhados"},
        {"tipo": "codigo", "titulo": "Dicionário dentro de dicionário", "linhas": [
            ("aluno = {", None),
            ("    'nome': 'Ana',", None),
            ("    'contato': {", None),
            ("        'email': 'ana@email.com',", None),
            ("        'telefone': '11 99999-9999'", None),
            ("    },", None),
            ("    'notas': [8.5, 9.0, 7.0]", None),
            ("}", None),
            ("print(aluno['contato']['email'])", "# ana@email.com"),
            ("print(aluno['notas'][0])", "# 8.5"),
        ]},

        {"tipo": "secao", "titulo": "Métodos úteis (resumo)"},
        {"tipo": "tabela",
         "cabecalho": ["Método", "O que faz"],
         "larguras": [0.28, 0.72], "mono": [0],
         "linhas": [
            ["keys()", "Retorna todas as chaves."],
            ["values()", "Retorna todos os valores."],
            ["items()", "Retorna pares (chave, valor)."],
            ["get()", "Acessa um valor com segurança."],
            ["update()", "Atualiza ou adiciona pares."],
            ["pop()", "Remove e retorna o valor."],
            ["popitem()", "Remove o último par inserido."],
            ["clear()", "Remove todos os itens."],
            ["copy()", "Cria uma cópia rasa."],
         ]},

        {"tipo": "secao", "titulo": "Exercício: sistema de biblioteca"},
        {"tipo": "paragrafo",
         "texto": "Um sistema que gerencia livros, onde <b>cada livro é um "
                  "dicionário</b>. Permite cadastrar, listar, buscar, emprestar, "
                  "devolver e remover. Cada livro guarda: título, autor, ano, "
                  "gênero e disponível (True/False)."},
        {"tipo": "codigo", "titulo": "biblioteca.py", "linhas": [
            ("biblioteca = []  # cada livro é um dicionário", None),
            ("", None),
            ("def cadastrar():", None),
            ("    livro = {", None),
            ("        'titulo': input('Título: '),", None),
            ("        'autor': input('Autor: '),", None),
            ("        'ano': input('Ano: '),", None),
            ("        'genero': input('Gênero: '),", None),
            ("        'disponivel': True,", None),
            ("    }", None),
            ("    biblioteca.append(livro)", None),
            ("    print('Livro cadastrado!')", None),
            ("", None),
            ("def listar():", None),
            ("    if not biblioteca:", None),
            ("        print('Nenhum livro cadastrado.')", None),
            ("        return", None),
            ("    for livro in biblioteca:", None),
            ("        estado = 'Disponível' if livro['disponivel'] else 'Emprestado'", None),
            ("        print(livro['titulo'], '-', livro['autor'], '(', estado, ')')", None),
            ("", None),
            ("def buscar():", None),
            ("    termo = input('Título buscado: ').lower()", None),
            ("    for livro in biblioteca:", None),
            ("        if termo in livro['titulo'].lower():", None),
            ("            print(livro)", None),
            ("", None),
            ("def emprestar():", None),
            ("    termo = input('Título: ').lower()", None),
            ("    for livro in biblioteca:", None),
            ("        if livro['titulo'].lower() == termo and livro['disponivel']:", None),
            ("            livro['disponivel'] = False", None),
            ("            print('Empréstimo realizado!')", None),
            ("            return", None),
            ("    print('Livro indisponível.')", None),
            ("", None),
            ("# (devolver e remover seguem a mesma lógica, mudando o estado/lista)", None),
            ("", None),
            ("while True:", None),
            ("    print('1-Cadastrar 2-Listar 3-Buscar 4-Emprestar 7-Sair')", None),
            ("    opcao = input('Escolha: ')", None),
            ("    if opcao == '1': cadastrar()", None),
            ("    elif opcao == '2': listar()", None),
            ("    elif opcao == '3': buscar()", None),
            ("    elif opcao == '4': emprestar()", None),
            ("    elif opcao == '7': break", None),
        ]},

        {"tipo": "callout", "titulo": "O que praticamos aqui",
         "texto": [
            "Usamos dicionários para representar dados de forma estruturada.",
            "Cada livro é identificado por suas chaves (título, autor, ano...).",
            "Exploramos inclusão, busca, atualização e remoção de itens.",
            "Combinamos dicionários com listas, booleanos e funções.",
         ]},

        {"tipo": "callout", "titulo": "Dica final + boas práticas",
         "cor": "#FFD43B",
         "texto": [
            "Dicionários modelam dados do mundo real com clareza.",
            "Use chaves significativas e consistentes; evite duplicadas.",
            "Prefira .get() para acessos seguros (sem erro).",
            "Mantenha o código organizado em funções pequenas.",
         ]},
    ],
}
