# -*- coding: utf-8 -*-
"""Conteudo: EasyAnsi em Python."""

from ..tema import TEMA_PYTHON

SPEC = {
    "tema": TEMA_PYTHON,
    "topico": "EASYANSI",
    "destaque": "EM PYTHON",
    "subtitulo": "Cores no terminal de forma simples",
    "simbolo": "//",
    "blocos": [
        {"tipo": "secao", "titulo": "Instalação"},
        {"tipo": "codigo", "linhas": [
            ("pip install py-easyansi", None),
            ("", None),
            ("# ou a partir do código-fonte:", None),
            ("pip install -e C:/caminho/para/EasyAnsi", None),
        ]},
        {"tipo": "paragrafo",
         "texto": "Requisitos: Python 3.8+ e terminal com suporte ANSI (Windows 10+ já funciona)."},

        {"tipo": "secao", "titulo": "Por que usar EasyAnsi?"},
        {"tipo": "paragrafo",
         "texto": "EasyAnsi foi criada para quem quer cor no terminal sem aprender uma biblioteca "
                  "pesada. Você escreve a cor dentro da string, como numa f-string."},
        {"tipo": "tabela",
         "titulo_tabela": "EasyAnsi x bibliotecas mais complexas",
         "cabecalho": ["Necessidade", "EasyAnsi", "Alternativas pesadas"],
         "larguras": [0.28, 0.36, 0.36],
         "mono": [0],
         "linhas": [
            ["Começar rápido", "from easyansi import eprint", "Configurar Console, markup"],
            ["Colorir uma palavra", "//red/{valor}/red", "Montar objetos Text"],
            ["Mensagem de sucesso", "success('Pronto')", "Criar renderizável"],
            ["Log colorido", "setup_logging()", "Handlers, temas, plugins"],
            ["Tag escrita errada", "Vira texto normal", "Pode quebrar o programa"],
         ]},
        {"tipo": "callout", "titulo": "Filosofia da biblioteca",
         "texto": [
            "Menos conceitos, menos imports.",
            "Comandos fáceis de lembrar no dia a dia.",
            "Fail-safe: URLs e tags desconhecidas não quebram a saída.",
         ]},

        {"tipo": "secao", "titulo": "Sintaxe //cor/texto/cor"},
        {"tipo": "tabela",
         "titulo_tabela": "Abertura e fechamento",
         "cabecalho": ["Padrão", "Significado", "Exemplo"],
         "larguras": [0.20, 0.36, 0.44],
         "mono": [0],
         "linhas": [
            ["//nome/", "Abre tag de estilo", "//red/"],
            ["/nome", "Fecha tag explicitamente", "/red"],
            ["//", "Fecha última tag aberta", "//green/texto//"],
         ]},
        {"tipo": "codigo", "linhas": [
            ("from easyansi import eprint", None),
            ("", None),
            ("eprint('//green/Olá, mundo!/green')", None),
            ("eprint('Sobrou //red/1/red item no estoque')", None),
            ("eprint('Acesse https://exemplo.com')  # URL intacta", None),
        ]},
        {"tipo": "callout", "titulo": "Fail-safe",
         "texto": [
            "Somente nomes conhecidos viram cor.",
            "//erro/texto/erro vira texto puro (não quebra).",
            "URLs com // permanecem literais.",
         ]},

        {"tipo": "secao", "titulo": "activate() vs eprint/einput"},
        {"tipo": "fluxo", "etapas": ["Script novo?", "Sim: activate()", "Não: eprint/einput"]},
        {"tipo": "paragrafo",
         "texto": "Com activate(), print e input normais passam a interpretar as tags EasyAnsi:"},
        {"tipo": "codigo", "linhas": [
            ("import easyansi", None),
            ("easyansi.activate()", None),
            ("", None),
            ("print('//green/Tudo certo!/green')", None),
            ("nome = input('Digite //cyan/seu nome/cyan: ')", None),
            ("easyansi.deactivate()  # restaura originais", None),
        ]},
        {"tipo": "paragrafo", "texto": "Alternativa explícita (sem alterar print global):"},
        {"tipo": "codigo", "linhas": [
            ("from easyansi import eprint, einput, fmt", None),
            ("", None),
            ("eprint('//green/Tudo certo!/green')", None),
            ("nome = einput('Digite //cyan/seu nome/cyan: ')", None),
            ("mensagem = fmt('//yellow/aviso/yellow')", None),
        ]},

        {"tipo": "secao", "titulo": "Atalhos e mensagens de status"},
        {"tipo": "paragrafo", "texto": "Atalhos de cor — ideais para autocomplete no editor:"},
        {"tipo": "codigo", "linhas": [
            ("from easyansi import red, green, yellow, blue, bold", None),
            ("", None),
            ("print(red('erro'), green('ok'), yellow('aviso'))", None),
            ("print(bold(red('crítico')))  # encadeamento", None),
        ]},
        {"tipo": "paragrafo", "texto": "Mensagens prontas para o dia a dia:"},
        {"tipo": "codigo", "linhas": [
            ("from easyansi import success, error, warning, info", None),
            ("", None),
            ("success('Salvo com sucesso')", None),
            ("error('Falha ao conectar')", None),
            ("warning('Conexão lenta')", None),
            ("info('Rodando na porta 8080')", None),
        ]},
        {"tipo": "tabela",
         "titulo_tabela": "Referência rápida de atalhos",
         "cabecalho": ["Função", "Uso típico"],
         "larguras": [0.34, 0.66],
         "mono": [0],
         "linhas": [
            ["red(), green(), ...", "Destacar palavras isoladas"],
            ["bold(), italic(), ...", "Enfatizar títulos e notas"],
            ["success(), error()", "Feedback de operação"],
            ["style('bold-blue', txt)", "Combo personalizado"],
         ]},

        {"tipo": "secao", "titulo": "Títulos, paint e f-strings"},
        {"tipo": "codigo", "linhas": [
            ("from easyansi import title, t, paint, ask, activate", None),
            ("", None),
            ("activate()", None),
            ("print(title('CADASTRO DE ALUNOS', '='))", None),
            ("print(t('MENU', '~', style='bold-blue'))", None),
            ("print(paint('Texto inteiro azul', 'bold-blue'))", None),
            ("nome = ask('Qual seu nome?', prompt_style='bold-blue')", None),
        ]},
        {"tipo": "paragrafo", "texto": "Funciona dentro de f-strings com variáveis:"},
        {"tipo": "codigo", "linhas": [
            ("pontos = 42", None),
            ("print(f'Resultado: //green/{pontos}/green pontos')", None),
            ("print(f'Nota //bold-blue/{7.5}/bold-blue em Matemática')", None),
        ]},
        {"tipo": "callout", "titulo": "Dica sobre input colorido",
         "texto": [
            "O terminal não colore em tempo real o que você digita.",
            "ask() colore o prompt; a resposta aparece colorida ao imprimir depois.",
         ]},

        {"tipo": "secao", "titulo": "Estilos combinados, fundos e hex"},
        {"tipo": "paragrafo", "texto": "Combine estilos com hífen: bold-blue, italic-underline-red."},
        {"tipo": "codigo", "linhas": [
            ("print('//bold-blue/cabeçalho/bold-blue')", None),
            ("print('//italic-underline-magenta/destaque/')", None),
            ("print('//bg-yellow/texto em fundo amarelo/bg-yellow')", None),
            ("print('//#ff8800/laranja exato/#ff8800')", None),
            ("print('//negrito-vermelho/erro em português/negrito-vermelho')", None),
        ]},
        {"tipo": "tabela",
         "titulo_tabela": "Variações de cor e estilo",
         "cabecalho": ["Tipo", "Tag", "Exemplo"],
         "larguras": [0.20, 0.26, 0.54],
         "mono": [0, 1],
         "linhas": [
            ["Estilo + cor", "bold-blue", "//bold-blue/texto/bold-blue"],
            ["Fundo", "bg-yellow", "//bg-yellow/aviso/bg-yellow"],
            ["Hex", "#ff8800", "//#ff8800/laranja/#ff8800"],
            ["PT", "negrito-vermelho", "//negrito-vermelho/erro/"],
         ]},

        {"tipo": "secao", "titulo": "Logging colorido e preview()"},
        {"tipo": "codigo", "linhas": [
            ("import logging", None),
            ("from easyansi.logging import setup_logging", None),
            ("", None),
            ("setup_logging(level=logging.INFO)", None),
            ("logging.info('Servidor iniciado')", None),
            ("logging.warning('Cache desatualizado')", None),
            ("logging.error('Falha ao conectar')", None),
        ]},
        {"tipo": "tabela",
         "titulo_tabela": "Cores por nível de log",
         "cabecalho": ["Nível", "Cor padrão"],
         "larguras": [0.30, 0.70],
         "mono": [0],
         "linhas": [
            ["DEBUG", "dim"],
            ["INFO", "cyan"],
            ["WARNING", "yellow"],
            ["ERROR", "red"],
            ["CRITICAL", "bold-red"],
         ]},
        {"tipo": "paragrafo", "texto": "Para ver todas as cores disponíveis no terminal:"},
        {"tipo": "codigo", "linhas": [
            ("import easyansi", None),
            ("easyansi.preview()", None),
        ]},

        {"tipo": "secao", "titulo": "Comportamento inteligente da saída"},
        {"tipo": "fluxo", "etapas": ["Terminal?", "Pipe/redir?", "NO_COLOR?", "Aplicar cor"]},
        {"tipo": "tabela",
         "cabecalho": ["Condição", "Comportamento"],
         "larguras": [0.42, 0.58],
         "linhas": [
            ["Terminal interativo (TTY)", "Cores ANSI aplicadas"],
            ["Saída em pipe / arquivo", "Texto limpo (sem escape)"],
            ["Variável NO_COLOR", "Texto limpo"],
            ["FORCE_COLOR definido", "Cores forçadas"],
         ]},

        {"tipo": "secao", "titulo": "Exercício prático — menu de notas"},
        {"tipo": "codigo", "linhas": [
            ("import easyansi", None),
            ("easyansi.activate()", None),
            ("", None),
            ("print(easyansi.title('NOTAS DO ALUNO', '='))", None),
            ("print('//cyan/1/cyan Listar  //cyan/2/cyan Cadastrar  //cyan/0/cyan Sair')", None),
            ("opcao = input('Escolha: ')", None),
            ("if opcao == '1': print('//green/Notas carregadas/green')", None),
            ("elif opcao == '2': print('//yellow/Cadastro em breve/yellow')", None),
            ("else: print('//dim/Encerrando/dim')", None),
        ]},

        {"tipo": "secao", "titulo": "Cola rápida da API"},
        {"tipo": "paragrafo",
         "texto": "fmt · eprint · einput · activate · title · t · paint · ask · preview · "
                  "red/green/bold · success/error/warning/info · setup_logging"},
    ],
}
