# -*- coding: utf-8 -*-
"""Conteudo: Listas em Python."""

from ..tema import TEMA_PYTHON

SPEC = {
    "tema": TEMA_PYTHON,
    "topico": "LISTAS",
    "destaque": "EM PYTHON",
    "subtitulo": "Guia completo com exemplos, resultados e explicacoes",
    "simbolo": "[ ]",
    "blocos": [
        {"tipo": "secao", "titulo": "O que sao listas?"},
        {"tipo": "checks", "itens": [
            "Listas sao colecoes <b>ordenadas</b> e <b>mutaveis</b>.",
            "Podem armazenar diferentes tipos de dados.",
            "Permitem elementos duplicados.",
            "Usamos colchetes [ ] para criar listas.",
            "Os indices comecam em 0.",
            "Muito usadas para armazenar e manipular conjuntos de dados.",
        ]},
        {"tipo": "secao", "titulo": "Criando listas"},
        {"tipo": "codigo", "titulo": "Formas de criar uma lista", "linhas": [
            ("numeros = [1, 2, 3, 4, 5]", "# lista de numeros"),
            ("frutas = ['maca', 'banana', 'laranja']", "# lista de strings"),
            ("mista = [10, 'Python', 3.14, True]", "# tipos diferentes"),
            ("vazia = []", "# lista vazia"),
            ("repeticao = [0] * 5", "# [0, 0, 0, 0, 0]"),
            ("copia = numeros.copy()", "# copia da lista"),
        ]},
        {"tipo": "secao", "titulo": "Operacoes e analise de listas"},
        {"tipo": "paragrafo",
         "texto": "Exemplos considerando <b>numeros = [10, 20, 30, 40, 50]</b>."},
        {"tipo": "tabela",
         "cabecalho": ["Comando", "Resultado", "Explicacao"],
         "larguras": [0.26, 0.30, 0.44], "mono": [0], "resultado": 1,
         "linhas": [
            ["numeros[0]", "10", "O indice 0 corresponde ao primeiro elemento."],
            ["numeros[2]", "30", "O indice 2 corresponde ao terceiro elemento."],
            ["numeros[-1]", "50", "Indices negativos comecam pelo final. -1 e o ultimo."],
            ["numeros[-2]", "40", "-2 e o penultimo elemento."],
            ["numeros[1:4]", "[20, 30, 40]", "Comeca no indice 1 (incluido) e para antes do 4."],
            ["numeros[0:3]", "[10, 20, 30]", "Retorna os elementos dos indices 0, 1 e 2."],
            ["numeros[2:]", "[30, 40, 50]", "Inicio em 2 e fim omitido: vai ate o ultimo."],
            ["numeros[:3]", "[10, 20, 30]", "Inicio omitido: do primeiro ate antes do indice 3."],
            ["numeros[:]", "[10,20,30,40,50]", "Tudo: copia da lista inteira."],
            ["numeros[-3:]", "[30, 40, 50]", "Os tres ultimos elementos."],
            ["len(numeros)", "5", "Quantidade de elementos da lista."],
            ["20 in numeros", "True", "Verifica se o valor 20 esta na lista."],
            ["100 in numeros", "False", "O valor 100 nao esta na lista."],
            ["numeros.count(10)", "1", "Quantas vezes o valor aparece na lista."],
            ["numeros.index(40)", "3", "Indice da primeira ocorrencia do valor."],
            ["numeros + [60, 70]", "[...,60,70]", "Concatena duas listas e retorna uma nova."],
            ["numeros * 2", "[...repetida]", "Repete a sequencia inteira da lista."],
            ["min(numeros)", "10", "Retorna o menor valor da lista."],
            ["max(numeros)", "50", "Retorna o maior valor da lista."],
            ["sum(numeros)", "150", "Soma todos os valores (se forem numericos)."],
         ]},
        {"tipo": "secao", "titulo": "Metodos mais utilizados"},
        {"tipo": "paragrafo", "texto": "Exemplos considerando <b>lista = [1, 2, 3]</b>."},
        {"tipo": "tabela",
         "cabecalho": ["Metodo", "Exemplo", "Resultado", "Explicacao"],
         "larguras": [0.18, 0.22, 0.18, 0.42], "mono": [0, 1], "resultado": 2,
         "linhas": [
            ["append(x)", "lista.append(4)", "[1,2,3,4]", "Adiciona um elemento ao final."],
            ["insert(i,x)", "lista.insert(1,99)", "[1,99,2,3]", "Insere x na posicao i."],
            ["extend(it)", "lista.extend([4,5])", "[1,2,3,4,5]", "Estende com os itens do iteravel."],
            ["remove(x)", "lista.remove(2)", "[1,3]", "Remove a primeira ocorrencia de x."],
            ["pop([i])", "lista.pop()", "3", "Remove e retorna o ultimo (ou o indice i)."],
            ["clear()", "lista.clear()", "[]", "Remove todos os elementos."],
            ["index(x)", "lista.index(1)", "0", "Indice da primeira ocorrencia de x."],
            ["count(x)", "lista.count(2)", "1", "Conta quantas vezes x aparece."],
            ["sort()", "lista.sort()", "[1,2,3]", "Ordena em ordem crescente (altera a lista)."],
            ["reverse()", "lista.reverse()", "[3,2,1]", "Inverte a ordem dos elementos."],
         ]},
        {"tipo": "secao", "titulo": "Ordenacao: sort() x sorted()"},
        {"tipo": "paragrafo",
         "texto": "As duas formas ordenam valores, mas se comportam de maneira diferente. "
                  "Escolha <b>sort()</b> quando quiser alterar a propria lista; use "
                  "<b>sorted()</b> quando precisar manter a original intacta."},
        {"tipo": "tabela",
         "cabecalho": ["Aspecto", "sort()", "sorted()"],
         "larguras": [0.36, 0.32, 0.32], "titulo_tabela": "Comparacao rapida",
         "linhas": [
            ["Altera a lista original?", "Sim", "Nao"],
            ["Retorno", "None", "Nova lista"],
            ["Onde usar", "Metodo: lista.sort()", "Funcao: sorted(lista)"],
            ["Lista original depois", "Fica ordenada", "Permanece igual"],
         ]},
        {"tipo": "paragrafo", "texto": "Exemplo com sort() — altera a lista original:"},
        {"tipo": "codigo", "titulo": "sort()", "linhas": [
            ("numeros = [3, 1, 4, 1, 5]", None),
            ("numeros.sort()", None),
            ("print(numeros)  # [1, 1, 3, 4, 5]", None),
        ]},
        {"tipo": "paragrafo", "texto": "Exemplo com sorted() — cria uma nova lista ordenada:"},
        {"tipo": "codigo", "titulo": "sorted()", "linhas": [
            ("original = [3, 1, 4, 1, 5]", None),
            ("ordenada = sorted(original)", None),
            ("print(ordenada)   # [1, 1, 3, 4, 5]", None),
            ("print(original)   # [3, 1, 4, 1, 5]  (nao mudou)", None),
        ]},
        {"tipo": "secao", "titulo": "Funcao set() — remover duplicatas"},
        {"tipo": "paragrafo",
         "texto": "A funcao <b>set()</b> converte uma lista em conjunto e remove valores "
                  "repetidos. Conjuntos nao garantem ordem; quando precisar de lista "
                  "novamente, use <b>list(set(lista))</b>."},
        {"tipo": "codigo", "titulo": "set()", "linhas": [
            ("presencas = ['P', 'F', 'P', 'X', 'F', 'P']", None),
            ("unicos = set(presencas)", None),
            ("print(unicos)              # {'P', 'F', 'X'} (sem repeticao)", None),
            ("lista_unica = list(set(presencas))", None),
            ("print(lista_unica)         # ordem pode variar", None),
        ]},
        {"tipo": "callout", "titulo": "Dica",
         "texto": "Use set() para contar itens distintos ou limpar repeticoes antes de analisar dados."},
        {"tipo": "secao", "titulo": "Fatiamento (slice) visual"},
        {"tipo": "paragrafo",
         "texto": "Considere <b>lista = [10, 20, 30, 40, 50]</b> e seus indices:"},
        {"tipo": "tabela",
         "cabecalho": ["Indice", "0", "1", "2", "3", "4"],
         "larguras": [0.20, 0.16, 0.16, 0.16, 0.16, 0.16], "mono": [0],
         "linhas": [["Valor", "10", "20", "30", "40", "50"]]},
        {"tipo": "tabela",
         "cabecalho": ["Expressao", "Resultado", "Leitura"],
         "larguras": [0.22, 0.26, 0.52], "mono": [0], "resultado": 1,
         "linhas": [
            ["lista[1:4]", "[20, 30, 40]", "Do indice 1 (incluido) ate antes do 4."],
            ["lista[2:]", "[30, 40, 50]", "Do indice 2 ate o final."],
            ["lista[:3]", "[10, 20, 30]", "Do inicio ate antes do indice 3."],
            ["lista[-3:]", "[30, 40, 50]", "Os tres ultimos elementos."],
         ]},
        {"tipo": "callout", "titulo": "Regra de ouro do fatiamento",
         "texto": "O indice inicial e INCLUIDO; o indice final NAO e incluido."},
        {"tipo": "secao", "titulo": "Exercicio: carrinho de compras"},
        {"tipo": "paragrafo",
         "texto": "Sistema de carrinho que permite adicionar, remover, atualizar a "
                  "quantidade, exibir o total e sair. Cada item e uma lista no "
                  "formato <b>[nome, preco, quantidade]</b> — ex.: ['Arroz', 4.99, 2]."},
        {"tipo": "codigo", "titulo": "carrinho.py", "linhas": [
            ("carrinho = []  # cada item: [nome, preco, quantidade]", None),
            ("", None),
            ("def adicionar():", None),
            ("    nome = input('Produto: ')", None),
            ("    preco = float(input('Preco: '))", None),
            ("    qtd = int(input('Quantidade: '))", None),
            ("    carrinho.append([nome, preco, qtd])", None),
            ("    print('Produto adicionado!')", None),
            ("", None),
            ("def remover():", None),
            ("    nome = input('Produto a remover: ')", None),
            ("    for item in carrinho:", None),
            ("        if item[0] == nome:", None),
            ("            carrinho.remove(item)", None),
            ("            print('Removido!')", None),
            ("            return", None),
            ("    print('Produto nao encontrado.')", None),
            ("", None),
            ("def atualizar():", None),
            ("    nome = input('Produto: ')", None),
            ("    for item in carrinho:", None),
            ("        if item[0] == nome:", None),
            ("            item[2] = int(input('Nova quantidade: '))", None),
            ("            print('Quantidade atualizada!')", None),
            ("", None),
            ("def exibir():", None),
            ("    total = 0", None),
            ("    for nome, preco, qtd in carrinho:", None),
            ("        subtotal = preco * qtd", None),
            ("        total += subtotal", None),
            ("        print(nome, qtd, 'x', preco, '=', subtotal)", None),
            ("    print('TOTAL:', total)", None),
            ("", None),
            ("while True:", None),
            ("    print('1-Adicionar 2-Remover 3-Atualizar 4-Exibir 5-Sair')", None),
            ("    opcao = input('Escolha: ')", None),
            ("    if opcao == '1': adicionar()", None),
            ("    elif opcao == '2': remover()", None),
            ("    elif opcao == '3': atualizar()", None),
            ("    elif opcao == '4': exibir()", None),
            ("    elif opcao == '5': break", None),
        ]},
        {"tipo": "callout", "titulo": "Dica final", "cor": "#FFD43B",
         "texto": "Listas sao extremamente versateis e aparecem em quase todo "
                  "programa. Domine os metodos e o fatiamento para manipular "
                  "dados com eficiencia."},
    ],
}
