# -*- coding: utf-8 -*-
"""Conteúdo: Listas em Python."""

from ..tema import TEMA_PYTHON

SPEC = {
    "tema": TEMA_PYTHON,
    "topico": "LISTAS",
    "destaque": "EM PYTHON",
    "subtitulo": "Guia completo com exemplos, resultados e explicações",
    "simbolo": "[ ]",
    "blocos": [
        {"tipo": "secao", "titulo": "O que são listas?"},
        {"tipo": "checks", "itens": [
            "Listas são coleções <b>ordenadas</b> e <b>mutáveis</b>.",
            "Podem armazenar diferentes tipos de dados.",
            "Permitem elementos duplicados.",
            "Usamos colchetes [ ] para criar listas.",
            "Os índices começam em 0.",
            "Muito usadas para armazenar e manipular conjuntos de dados.",
        ]},
        {"tipo": "secao", "titulo": "Criando listas"},
        {"tipo": "codigo", "titulo": "Formas de criar uma lista", "linhas": [
            ("numeros = [1, 2, 3, 4, 5]", "# lista de números"),
            ("frutas = ['maca', 'banana', 'laranja']", "# lista de strings"),
            ("mista = [10, 'Python', 3.14, True]", "# tipos diferentes"),
            ("vazia = []", "# lista vazia"),
            ("repeticao = [0] * 5", "# [0, 0, 0, 0, 0]"),
            ("copia = numeros.copy()", "# cópia da lista"),
        ]},
        {"tipo": "secao", "titulo": "Operações e análise de listas"},
        {"tipo": "paragrafo",
         "texto": "Exemplos considerando <b>numeros = [10, 20, 30, 40, 50]</b>."},
        {"tipo": "tabela",
         "cabecalho": ["Comando", "Resultado", "Explicação"],
         "larguras": [0.26, 0.30, 0.44], "mono": [0], "resultado": 1,
         "linhas": [
            ["numeros[0]", "10", "O índice 0 corresponde ao primeiro elemento."],
            ["numeros[2]", "30", "O índice 2 corresponde ao terceiro elemento."],
            ["numeros[-1]", "50", "Índices negativos começam pelo final. -1 é o último."],
            ["numeros[-2]", "40", "-2 é o penúltimo elemento."],
            ["numeros[1:4]", "[20, 30, 40]", "Começa no índice 1 (incluído) e para antes do 4."],
            ["numeros[0:3]", "[10, 20, 30]", "Retorna os elementos dos índices 0, 1 e 2."],
            ["numeros[2:]", "[30, 40, 50]", "Início em 2 e fim omitido: vai até o último."],
            ["numeros[:3]", "[10, 20, 30]", "Início omitido: do primeiro até antes do índice 3."],
            ["numeros[:]", "[10,20,30,40,50]", "Tudo: cópia da lista inteira."],
            ["numeros[-3:]", "[30, 40, 50]", "Os três últimos elementos."],
            ["len(numeros)", "5", "Quantidade de elementos da lista."],
            ["20 in numeros", "True", "Verifica se o valor 20 está na lista."],
            ["100 in numeros", "False", "O valor 100 não está na lista."],
            ["numeros.count(10)", "1", "Quantas vezes o valor aparece na lista."],
            ["numeros.index(40)", "3", "Índice da primeira ocorrência do valor."],
            ["numeros + [60, 70]", "[...,60,70]", "Concatena duas listas e retorna uma nova."],
            ["numeros * 2", "[...repetida]", "Repete a sequência inteira da lista."],
            ["min(numeros)", "10", "Retorna o menor valor da lista."],
            ["max(numeros)", "50", "Retorna o maior valor da lista."],
            ["sum(numeros)", "150", "Soma todos os valores (se forem numéricos)."],
         ]},
        {"tipo": "secao", "titulo": "Métodos mais utilizados"},
        {"tipo": "paragrafo", "texto": "Exemplos considerando <b>lista = [1, 2, 3]</b>."},
        {"tipo": "tabela",
         "cabecalho": ["Método", "Exemplo", "Resultado", "Explicação"],
         "larguras": [0.18, 0.22, 0.18, 0.42], "mono": [0, 1], "resultado": 2,
         "linhas": [
            ["append(x)", "lista.append(4)", "[1,2,3,4]", "Adiciona um elemento ao final."],
            ["insert(i,x)", "lista.insert(1,99)", "[1,99,2,3]", "Insere x na posição i."],
            ["extend(it)", "lista.extend([4,5])", "[1,2,3,4,5]", "Estende com os itens do iterável."],
            ["remove(x)", "lista.remove(2)", "[1,3]", "Remove a primeira ocorrência de x."],
            ["pop([i])", "lista.pop()", "3", "Remove e retorna o último (ou o índice i)."],
            ["clear()", "lista.clear()", "[]", "Remove todos os elementos."],
            ["index(x)", "lista.index(1)", "0", "Índice da primeira ocorrência de x."],
            ["count(x)", "lista.count(2)", "1", "Conta quantas vezes x aparece."],
            ["sort()", "lista.sort()", "[1,2,3]", "Ordena em ordem crescente (altera a lista)."],
            ["reverse()", "lista.reverse()", "[3,2,1]", "Inverte a ordem dos elementos."],
         ]},
        {"tipo": "secao", "titulo": "Ordenação: sort() x sorted()"},
        {"tipo": "paragrafo",
         "texto": "As duas formas ordenam valores, mas se comportam de maneira diferente. "
                  "Escolha <b>sort()</b> quando quiser alterar a própria lista; use "
                  "<b>sorted()</b> quando precisar manter a original intacta."},
        {"tipo": "tabela",
         "cabecalho": ["Aspecto", "sort()", "sorted()"],
         "larguras": [0.36, 0.32, 0.32], "titulo_tabela": "Comparação rápida",
         "linhas": [
            ["Altera a lista original?", "Sim", "Não"],
            ["Retorno", "None", "Nova lista"],
            ["Onde usar", "Método: lista.sort()", "Função: sorted(lista)"],
            ["Lista original depois", "Fica ordenada", "Permanece igual"],
         ]},
        {"tipo": "paragrafo", "texto": "Exemplo com sort() — altera a lista original:"},
        {"tipo": "codigo", "titulo": "sort()", "linhas": [
            ("numeros = [3, 1, 4, 1, 5]", None),
            ("numeros.sort()", None),
            ("print(numeros)  # [1, 1, 3, 4, 5]", None),
        ]},
        {"tipo": "paragrafo", "texto": "Exemplo com sorted() — cria uma nova lista ordenada:"},
        {"tipo": "codigo", "titulo": "sorted()", "linhas": [
            ("original = [3, 1, 4, 1, 5]", None),
            ("ordenada = sorted(original)", None),
            ("print(ordenada)   # [1, 1, 3, 4, 5]", None),
            ("print(original)   # [3, 1, 4, 1, 5]  (não mudou)", None),
        ]},
        {"tipo": "secao", "titulo": "Função set() — remover duplicatas"},
        {"tipo": "paragrafo",
         "texto": "A função <b>set()</b> converte uma lista em conjunto e remove valores "
                  "repetidos. Conjuntos não garantem ordem; quando precisar de lista "
                  "novamente, use <b>list(set(lista))</b>."},
        {"tipo": "codigo", "titulo": "set()", "linhas": [
            ("presencas = ['P', 'F', 'P', 'X', 'F', 'P']", None),
            ("unicos = set(presencas)", None),
            ("print(unicos)              # {'P', 'F', 'X'} (sem repetição)", None),
            ("lista_unica = list(set(presencas))", None),
            ("print(lista_unica)         # ordem pode variar", None),
        ]},
        {"tipo": "callout", "titulo": "Dica",
         "texto": "Use set() para contar itens distintos ou limpar repetições antes de analisar dados."},
        {"tipo": "secao", "titulo": "Fatiamento (slice) visual"},
        {"tipo": "paragrafo",
         "texto": "Considere <b>lista = [10, 20, 30, 40, 50]</b> e seus índices:"},
        {"tipo": "tabela",
         "cabecalho": ["Índice", "0", "1", "2", "3", "4"],
         "larguras": [0.20, 0.16, 0.16, 0.16, 0.16, 0.16], "mono": [0],
         "linhas": [["Valor", "10", "20", "30", "40", "50"]]},
        {"tipo": "tabela",
         "cabecalho": ["Expressão", "Resultado", "Leitura"],
         "larguras": [0.22, 0.26, 0.52], "mono": [0], "resultado": 1,
         "linhas": [
            ["lista[1:4]", "[20, 30, 40]", "Do índice 1 (incluído) até antes do 4."],
            ["lista[2:]", "[30, 40, 50]", "Do índice 2 até o final."],
            ["lista[:3]", "[10, 20, 30]", "Do início até antes do índice 3."],
            ["lista[-3:]", "[30, 40, 50]", "Os três últimos elementos."],
         ]},
        {"tipo": "callout", "titulo": "Regra de ouro do fatiamento",
         "texto": "O índice inicial é INCLUÍDO; o índice final NÃO é incluído."},
        {"tipo": "secao", "titulo": "Exercício: carrinho de compras"},
        {"tipo": "paragrafo",
         "texto": "Sistema de carrinho que permite adicionar, remover, atualizar a "
                  "quantidade, exibir o total e sair. Cada item é uma lista no "
                  "formato <b>[nome, preço, quantidade]</b> — ex.: ['Arroz', 4.99, 2]."},
        {"tipo": "codigo", "titulo": "carrinho.py", "linhas": [
            ("carrinho = []  # cada item: [nome, preco, quantidade]", None),
            ("", None),
            ("def adicionar():", None),
            ("    nome = input('Produto: ')", None),
            ("    preco = float(input('Preço: '))", None),
            ("    qtd = int(input('Quantidade: '))", None),
            ("    carrinho.append([nome, preco, qtd])", None),
            ("    print('Produto adicionado!')", None),
            ("", None),
            ("def remover():", None),
            ("    nome = input('Produto a remover: ')", None),
            ("    for item in carrinho:", None),
            ("        if item[0] == nome:", None),
            ("            carrinho.remove(item)", None),
            ("            print('Removido!')", None),
            ("            return", None),
            ("    print('Produto não encontrado.')", None),
            ("", None),
            ("def atualizar():", None),
            ("    nome = input('Produto: ')", None),
            ("    for item in carrinho:", None),
            ("        if item[0] == nome:", None),
            ("            item[2] = int(input('Nova quantidade: '))", None),
            ("            print('Quantidade atualizada!')", None),
            ("", None),
            ("def exibir():", None),
            ("    total = 0", None),
            ("    for nome, preco, qtd in carrinho:", None),
            ("        subtotal = preco * qtd", None),
            ("        total += subtotal", None),
            ("        print(nome, qtd, 'x', preco, '=', subtotal)", None),
            ("    print('TOTAL:', total)", None),
            ("", None),
            ("while True:", None),
            ("    print('1-Adicionar 2-Remover 3-Atualizar 4-Exibir 5-Sair')", None),
            ("    opcao = input('Escolha: ')", None),
            ("    if opcao == '1': adicionar()", None),
            ("    elif opcao == '2': remover()", None),
            ("    elif opcao == '3': atualizar()", None),
            ("    elif opcao == '4': exibir()", None),
            ("    elif opcao == '5': break", None),
        ]},
        {"tipo": "callout", "titulo": "Dica final", "cor": "#FFD43B",
         "texto": "Listas são extremamente versáteis e aparecem em quase todo "
                  "programa. Domine os métodos e o fatiamento para manipular "
                  "dados com eficiência."},
    ],
}
